<?php

namespace App\Controllers;

class ReportController extends BaseController
{
    public function index()
    {
        $transaksi = session()->get('transaksi_data') ?? [];
        $totalPendapatan = array_sum(array_column($transaksi, 'total'));
        $totalTransaksi = count($transaksi);
        $rataRata = $totalTransaksi > 0 ? $totalPendapatan / $totalTransaksi : 0;

        $data = [
            'transaksi'       => $transaksi,
            'totalPendapatan' => $totalPendapatan,
            'totalTransaksi'  => $totalTransaksi,
            'rataRata'        => $rataRata,
        ];

        return view('laporan/index', $data);
    }

    public function generatePDF()
    {
        $transaksi = session()->get('transaksi_data') ?? [];
        $totalPendapatan = array_sum(array_column($transaksi, 'total'));

        $html = '
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Laporan ALLAUNDRY</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                h1 { color: #0ea5e9; text-align: center; }
                h2 { color: #0369a1; }
                table { width: 100%; border-collapse: collapse; margin: 20px 0; }
                th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
                th { background-color: #0ea5e9; color: white; }
                .total { font-size: 18px; font-weight: bold; color: #0369a1; }
                .header-info { text-align: center; margin-bottom: 30px; }
            </style>
        </head>
        <body>
            <div class="header-info">
                <h1>🧺 ALLAUNDRY</h1>
                <p>Laporan Transaksi Laundry</p>
                <p>Tanggal: ' . date('d-m-Y H:i:s') . '</p>
            </div>
            
            <h2>Ringkasan</h2>
            <p><strong>Total Transaksi:</strong> ' . count($transaksi) . '</p>
            <p class="total"><strong>Total Pendapatan:</strong> Rp ' . number_format($totalPendapatan, 0, ',', '.') . '</p>
            
            <h2>Detail Transaksi</h2>
            <table>
                <thead>
                    <tr>
                        <th>No. Transaksi</th>
                        <th>Pelanggan</th>
                        <th>Items</th>
                        <th>Total</th>
                        <th>Status</th>
                        <th>Tanggal</th>
                    </tr>
                </thead>
                <tbody>';
        
        foreach ($transaksi as $t) {
            $html .= '
                    <tr>
                        <td>' . $t['no_transaksi'] . '</td>
                        <td>' . $t['pelanggan'] . '</td>
                        <td>' . $t['items'] . '</td>
                        <td>Rp ' . number_format($t['total'], 0, ',', '.') . '</td>
                        <td>' . $t['status'] . '</td>
                        <td>' . $t['tanggal'] . '</td>
                    </tr>';
        }
        
        $html .= '
                </tbody>
            </table>
            
            <div style="margin-top: 50px; text-align: center;">
                <p>Terima kasih telah menggunakan ALLAUNDRY</p>
                <p><em>Generated by System - ' . date('Y') . '</em></p>
            </div>
        </body>
        </html>';

        // Return HTML yang bisa di-print sebagai PDF
        return $this->response
            ->setHeader('Content-Type', 'text/html')
            ->setHeader('Content-Disposition', 'inline; filename="laporan-allalaundry.html"')
            ->setBody($html);
    }
}